Dev slit bis
sibirrer/lenstronomy pull request #207
Opened 2020-09-02 15:51 UTC by aymgal

This PR replaces #139 , with a much simpler integration to lenstronomy.

The general idea now is: when a source light profile such as `'SLIT_STARLETS'` is chosen, the `ImageModel` class (and subsequently `ImageLinearFit`) switches to "pixel-based modelling" mode. It effectively replaces the WLS that usually solves for linear amplitudes by the external SLITronomy solver.

In SLITronomy, three setups are supported:
- pixel-based modelling of source only (no lens light nor point source should be set)
- pixel-based modelling of source and lens light (no point source should be set)
- pixel-based modelling of source and point-sources light (no lens light should be set)

Supported light profiles are `'SLIT_STARLETS'` and `'SLIT_STARLETS_GEN2'`. The check correctness of chosen profiles is performed by the SLITronomy utility `lenstronomy.Util.class_util.create_solver_class()`, which returns the right "sparse solver" class (or raises errors if the configuration is not supported).

Differential extinction is not supported yet.

Additionally, you can add to the `kwargs_special` two sampled parameters to marginalise over offsets between the pixelated source grid and data grid.

I leaved the (drafted) old PR opened, that can help for the discussion (the number of commits is rather large sorry, but it mainly come from from the older PR).

2020-09-02 17:01 UTC, sibirrer commented on requirements.txt
> +-e git://github.com/aymgal/slitronomy.git@master#egg=slitronomy
yes, I would also like to look into slitronomy and it's testing to make sure there is a stable distribution to comply with astropy affiliation

2020-09-02 17:09 UTC, sibirrer commented on test/test_ImSim/test_Numerics/test_convolution.py
> +    def test_copy_transpose(self):
the test coverage dropped about 2%. I don't comment on the tests but would be great to have good test coverage. There might be a few lines that can not be tested due to dependencies but most should be able to be tested (incl. raise statements).

2020-09-02 21:30 UTC, sibirrer commented
travis failed after the update

2020-09-02 21:32 UTC, aymgal commented
> travis failed after the update

Yes, I am not done with the changes (should not have pushed these commits actually 😉).

2020-09-02 21:34 UTC, sibirrer commented
> > travis failed after the update
> 
> Yes, I am not done with the changes (should not have pushed these commits actually 😉).

no worries! just ping me once you think it's ready for me to review. Thanks :)

2020-09-03 09:55 UTC, aymgal commented
The remaining big chunk of untested code are routines related to the external package pySAP (https://github.com/CEA-COSMIC/pysap) to perform efficient wavelet transforms.
When this package is not installed (or `force_no_pysap` set to `True`), python-only routines are called, which are tested.
In SLITronomy test routines, pySAP is used, so there it is properly tested. If you do want this to be tested also in lenstronomy as well, it would require changing the requirements/travis.yml to some extent to make sure pySAP is correctly compiled on the CI server (which sometimes can be really painful I must say...).

Otherwise please tell me anything needs to be improved :)

2020-09-03 17:03 UTC, sibirrer requested changes
Thanks a lot for the updates! Very close to merging. I have few clarification questions (see comments in code) and for the test coverage improvements. Looking at coveralls, is there a way to test the private functions _transform(), _inverse_transform() _coeffs2pysap()? I see that pySAP should not be imported for the tests and that this does not allow to test certain lines of code.
Then, once I approve the PR, before merging, can you release a new slitronomy PyPi version and update the PR with it such that I can merge with the sealed PyPi version.

2020-09-03 19:50 UTC, aymgal commented on lenstronomy/ImSim/image_linear_solve.py
> +            model = self.array_masked2image(wls_model)
The model returned by the PixelSolver is already defined as a 2d image with likelihood mask applied, so no need here.

2020-09-03 19:57 UTC, aymgal commented on lenstronomy/ImSim/image_linear_solve.py
>          :return: 1d array of surface brightness pixels of the optimal solution of the linear parameters to match the data
Indeed it's 2d, will fix that!

2020-09-03 19:57 UTC, aymgal commented on lenstronomy/ImSim/image_linear_solve.py
> +        :return: 1d array of surface brightness pixels of the optimal solution of the linear parameters to match the data
will be fixed in next commits as well

2020-09-03 20:01 UTC, aymgal commented on lenstronomy/ImSim/image_linear_solve.py
>          _, _, _, _ = self.update_linear_kwargs(param, kwargs_lens, kwargs_source, kwargs_lens_light, kwargs_ps)
`point_source_only` is deprecated indeed... And yes duplication can be avoided here, thanks for seeing this

2020-09-03 20:02 UTC, aymgal commented on lenstronomy/ImSim/image_model.py
> +            from slitronomy.Util.class_util import create_solver_class  # requirement on SLITronomy is exclusively here
Yes I reduced it to this single import. And this way there no obligation to install SLITronomy as well when no using corresponding light profiles

2020-09-03 20:18 UTC, aymgal commented on lenstronomy/LightModel/Profiles/starlets.py
> +            return False, None
Here is a quick notebook timeit, for decomposing a 100x100 image into starlet coefficients:
__with pySAP__: 452 µs ± 69.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
__with pure python__: 1.47 ms ± 44.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In SLITronomy starlet functions are called _a lot_ of times, so it plays significant role.
When only using the `SLIT_Starlets` profile for a few calls of decomposition/reconstruction methods, then it does not matter (and starts to matter again for really big images).

2020-09-03 20:19 UTC, aymgal commented on lenstronomy/LightModel/Profiles/starlets.py
> +            return False, None
Indeed a warning can be much more explicit, I will propose something in that direction

2020-09-03 20:52 UTC, aymgal commented
I further completed test coverage.
Concerning `_transform` and `_inverse_transform`... I am not sure how those can be tested, as they almost exclusively call pysap-related methods (now that `pysap2coeffs`/`coeffs2pysap` are tested). Is there some clever technique to deal with this?

2020-09-04 02:01 UTC, sibirrer approved these changes
This looks very good and I can formally approve it. The tests are sufficient to the level that they are possible. Thanks for putting your effort into this!
So now there are two remaining minor things:
- Warning if pySAP is not installed
- pointer to PyPi version of SLITronomy
I also looked at SLITronomy and it looks really good with good test coverage and documentation. One thing thought might be changed when releasing it on PyPi is the status (from beta to stable), if you feel comfortable. I know it's primarily beta because it still requires your fork of lenstronomy to run. The astropy community would probably like to see that dependencies are marked as stable. So I formally approve this PR and wait for the merge for these minor changes. Looking very much forward to push the merge button!

2020-09-07 14:46 UTC, aymgal commented
If added the warning message and released a stable PyPi version 0.3.2.

2020-09-07 15:38 UTC, sibirrer requested changes

2020-09-07 15:38 UTC, sibirrer commented on requirements.txt
> +slitronomy
Can you add a specific version number? This makes it more stable and makes sure that when a new slitronomy version is released, it goes through a PR to check compatibility.

2020-09-07 15:38 UTC, aymgal commented
I realize that the `image_pixelbased_solve` has to support stand-alone use as well (without calling `image_linear_solve`), typically for its argument `init_lens_light_model`. So I move back the call to `update_linear_kwargs` inside the method, despite the small duplication code... hope it's still ok like this

2020-09-07 15:39 UTC, aymgal commented on requirements.txt
> +slitronomy
Ok I will add it

2020-09-07 16:03 UTC, sibirrer approved these changes

2020-09-07 16:05 UTC, sibirrer commented
Very nice! I will merge now and then make a new lenstronomy PyPi release (overdue anyways).

2020-09-07 16:06 UTC, merged