regularize EPL at origin
sibirrer/lenstronomy pull request #211
Opened 2020-09-22 21:20 UTC by dangilman

I just implemented the property I want in the deflection angles alpha(0, 0) = 0 by replacing nan values with zero. The function can only be nan at the origin so it works

2020-09-22 22:20 UTC, sibirrer requested changes
Could you simplify things with `numpy.nan_to_num`? I don't see a specific test case that checks the case of turning nan's into zero. Thanks!

2020-09-22 22:20 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/epl.py
> +        if isinstance(alpha_real, float) or isinstance(alpha_real, int):
can you simplify this with this functionality in numpy? https://numpy.org/doc/stable/reference/generated/numpy.nan_to_num.html

2020-09-22 22:20 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/epl.py
> +        alpha_real, alpha_imag = self._regularize(alpha)
isn't this also an issue for derivatives and Hessians?

2020-09-22 23:06 UTC, dangilman commented
I added the numpy function. Passing in (x, y) = (0, 0) creates np.nan values inside the class that get output as zeros, but I added another test function that tests the new regularize function explicitly. And it is also an issue for hessian, but hessian is computed by calling derivatives so it is taken care of

2020-09-22 23:07 UTC, dangilman commented
nevermind, was looking at the wrong hessian class.... let me fix it for the hessian also

2020-09-22 23:22 UTC, dangilman commented
not really sure what to do with infinities... I just default them to plus/minus 1000

2020-09-23 00:14 UTC, sibirrer requested changes
I don't think you need the array and float/int distinction with the new routine. This will simplify things quite a bit.

2020-09-23 00:14 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/epl.py
> +        if isinstance(value, float) or isinstance(value, int):
do you need this part?

2020-09-23 00:14 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/epl.py
> +        out = np.nan_to_num(value, posinf=1e+3, neginf=-1e+3)
posinf and neginf do not need to be specified I think.

2020-09-23 00:14 UTC, sibirrer commented on test/test_LensModel/test_Profiles/test_epl.py
> +        value = np.nan
I was more thinking of putting in (0,0) and see whether you get regular behavior out

2020-09-23 00:29 UTC, dangilman commented on test/test_LensModel/test_Profiles/test_epl.py
> +        value = np.nan
I do that on line 111

2020-09-23 00:29 UTC, dangilman commented on lenstronomy/LensModel/Profiles/epl.py
> +        out = np.nan_to_num(value, posinf=1e+3, neginf=-1e+3)
I'll take them out

2020-09-23 00:29 UTC, dangilman commented on lenstronomy/LensModel/Profiles/epl.py
> +        if isinstance(value, float) or isinstance(value, int):
It serves only to keep the input and output data types the same. If you supply a float, without that check you get back a numpy array. I can take it out if you want

2020-09-23 00:31 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/epl.py
> +        if isinstance(value, float) or isinstance(value, int):
I had guessed that the nan_to_num keeps the same in and output format. It's worth testing and if confirmed, you don't need this.

2020-09-23 04:28 UTC, sibirrer approved these changes

2020-09-23 04:29 UTC, merged

2020-09-23 04:29 UTC, sibirrer commented
Thank you!