Remake optimizer
sibirrer/lenstronomy pull request #217
Opened 2020-11-21 04:09 UTC by dangilman

I finally got around to re-writing the Optimizer module. It is much cleaner now and more powerful with the new ParamsClass option, which can be user-specified. I put some examples in the param_manager file and included some useful hardcoded examples for reference

2020-11-21 05:01 UTC, sibirrer requested changes
Thank you very much for these changes and the clean-up of code. The code looks very clean. I have only documentation and minor design request for public vs. private functions. Unfortunately, travis-CI changed the policy and is not anymore freely available, so I have to come up with another solution to run integrated tests (especially for PR's and releases), so can not check test coverage at the moment. I hope I will have this fixed soon.

2020-11-21 06:23 UTC, dangilman commented on lenstronomy/LensModel/QuadOptimizer/fast_rayshooting.py
> +    def source_plane_penalty(self, args_lens, *args, **kwargs):
fixed

2020-11-21 06:23 UTC, dangilman commented on lenstronomy/LensModel/QuadOptimizer/fast_rayshooting.py
> +class FastRayShooting(object):
I added some more detail and renamed the class to MultiPlaneFast

2020-11-21 06:23 UTC, dangilman commented on lenstronomy/LensModel/QuadOptimizer/fast_rayshooting.py
> +        :param args_lens: an array of parameters being optimized
done

2020-11-21 06:24 UTC, dangilman commented on lenstronomy/LensModel/QuadOptimizer/fast_rayshooting.py
> +        :return: the position of each ray in the source plane
added some details

2020-11-21 06:24 UTC, dangilman commented on lenstronomy/LensModel/QuadOptimizer/fast_rayshooting.py
> +        self.foreground_rays = foreground_rays
I set it to private, and there is a function towards the bottom of the class that evaluates it if it is None and returns something if it is not None

2020-11-21 06:25 UTC, dangilman commented on lenstronomy/LensModel/QuadOptimizer/fast_rayshooting.py
> +        if self.foreground_rays is None:
done

2020-11-21 06:27 UTC, dangilman commented on lenstronomy/LensModel/QuadOptimizer/param_manager.py
> +# class ParamClass(object):
I intended to write different classes to combined disks and power laws (for example) and can just feed them into lenstronomy and try to do lens model optimizations with them. I thought since it is possible for someone to write their own param class and feed it to the optimizer I would put a commented-out example of what the class should look like. It makes no difference to me though, I can take it out

2020-11-21 06:31 UTC, dangilman commented on lenstronomy/LensModel/QuadOptimizer/param_manager.py
> +        if re_optimize:
I added a note in the documentation saying that if people want to use this for a different purpose they should write their own ParamClass and feed it to the Optimizer

2020-11-21 06:31 UTC, dangilman commented on lenstronomy/LensModel/QuadOptimizer/param_manager.py
> +        self.kwargs_lens = kwargs_lens_init
Yeah it gets accessed in the main Optimizer class

2020-11-21 06:31 UTC, dangilman commented on lenstronomy/LensModel/QuadOptimizer/param_manager.py
> +        self.shear_strength = shear_strength
made it private

2020-11-21 06:32 UTC, dangilman commented on lenstronomy/LensModel/QuadOptimizer/param_manager.py
> +    def to_vary_index(self):
fixed

2020-11-21 06:32 UTC, dangilman commented on lenstronomy/Sampling/Samplers/pso.py
> +        chi_square = [-2 * particle.fitness for particle in self.swarm]
I just tried it with multiprocessing and it worked fine

2020-11-21 07:06 UTC, dangilman commented
Ok I think I addressed all of you comments, let me know if I missed something

2020-11-21 18:53 UTC, dangilman commented
another option is I can just keep all of the classes in param_manager outside of lenstronomy

2020-11-21 23:54 UTC, sibirrer commented
Nice, thanks! If you add a test coverage for the re_optimize option of the bounds (see coverall report), then you'll even get the module to 100% test coverage. Then I can merge and if we need to re-design parts that should be doable without breaking the usage.

2020-11-22 02:45 UTC, sibirrer approved these changes

2020-11-22 02:45 UTC, merged