New lens model : elliptical density slice
sibirrer/lenstronomy pull request #225
Opened 2021-01-04 14:53 UTC by LyneVdV

This lens model has a constant surface density inside an ellipse and has 0. outside.
This model is based on Schramm 1994 (A toolbox for general elliptical gravitational lenses) : the general idea of the paper is to discretize a surface density of a galaxy into a sum of elliptical slices of denstity with different spatial extensions and orientations. The potential and deflections of one slice are known analytically (see Schramm 1994). This new lens model, called ElliSLICE, gathers the lensing quantites associated to one elliptical slice with constant surface density. 
It can be used to create complex models of galaxies with isophotal twists, change in ellipticity etc by assembling several elliptical slices with different intrinsic parameters. It can also be used in a fitting process but I have not tried it.
I tried to be explicit in the class definition and in the code. I also created and run different tests. Let me know if I have to change anything !

2021-01-04 16:22 UTC, sibirrer requested changes
Hi Lyne, thank you very much for the PR and this addition! Overall looks very good. I have some requests for testing and documentation. Other than that happy to merge. Let me know if you have questions.

2021-01-04 16:22 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/elliptical_density_slice.py
> +    in radian, and with constant surface mass density 'sigma_0'
Can you add a mathematical formula directly to this documentation? I know it's not been done for all the old models but I would like to change that in the long run. One example could be found here: https://github.com/sibirrer/lenstronomy/blob/master/lenstronomy/LensModel/Profiles/p_jaffe.py

2021-01-04 16:22 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/elliptical_density_slice.py
> +        else :
these lines of code are note testes. See: https://github.com/sibirrer/lenstronomy/blob/master/lenstronomy/LensModel/Profiles/p_jaffe.py

2021-01-04 16:22 UTC, sibirrer commented on test/test_LensModel/test_Profiles/test_elliptical_density_slice.py
> +    tests tthe elliptical slice lens model
minor typo :)

2021-01-04 16:22 UTC, sibirrer commented on test/test_LensModel/test_Profiles/test_elliptical_density_slice.py
> +        npt.assert_almost_equal(values[1], values[2], decimal=5)
Is there a way to test a correspondence with a different profile (such as a point source outside of the elliptical shell)? Just wondering, and if so, might be good to demonstrate it in the tests.

2021-01-04 16:22 UTC, sibirrer commented on test/test_LensModel/test_numeric_lens_differentials.py
> +    def test_elli_slice(self):
can you add a spacing between the test functions?

2021-01-04 16:22 UTC, sibirrer commented on test/test_LensModel/test_numeric_lens_differentials.py
> +        kwargs = {'a':1., 'b':2., 'psi':30*np.pi/180., 'sigma_0':5., 'center_x':1., 'center_y':2.}
the differential test is made at a default (1,1) location (maybe I need to change that more broadly in general). For your case, the differentials are only tested inside of the ellipse. Can you add a second scenario where the differential is performed outside? This is also reflected in the test coverage.

2021-01-05 10:39 UTC, LyneVdV commented on lenstronomy/LensModel/Profiles/elliptical_density_slice.py
> +    in radian, and with constant surface mass density 'sigma_0'
Really nice idea to have a mathematical formula for all models !

2021-01-05 10:41 UTC, LyneVdV commented on lenstronomy/LensModel/Profiles/elliptical_density_slice.py
> +        else :
Solved !

2021-01-05 11:09 UTC, LyneVdV commented on test/test_LensModel/test_Profiles/test_elliptical_density_slice.py
> +        npt.assert_almost_equal(values[1], values[2], decimal=5)
Not exactly : outside the elliptical slice, the potential symmetry is confocal and is getting rounder and rounder as you move away from the slice and thus _tend_ to mimic a point mass model at large distance. So there is no exact correspondence to test. If you really want to, I can try to find the conversion factor between my model and the point mass model and see at which distance I have to go before having a correspondence at x decimals. It will be a fine tuning depending on the slice parameters so I don't think it is really needed here.

2021-01-05 11:15 UTC, LyneVdV commented on test/test_LensModel/test_numeric_lens_differentials.py
> +        kwargs = {'a':1., 'b':2., 'psi':30*np.pi/180., 'sigma_0':5., 'center_x':1., 'center_y':2.}
You have already broaden it with x = np.linspace(start=0.1, stop=5.5, num=10) and y = np.zeros_like(x) ! I changed the parameters and added a line so that it can go inside and outside the slice and also on and off the ellipse axis.

2021-01-05 11:24 UTC, LyneVdV commented
Hi Simon ! 
I implemented the changes and even found a typo that was slowing down the code.
For the comparison with the point_mass model, let me know what you think.
Have a nice day !

2021-01-05 16:45 UTC, sibirrer commented on test/test_LensModel/test_Profiles/test_elliptical_density_slice.py
> +        npt.assert_almost_equal(values[1], values[2], decimal=5)
I think it's fine not having it in the code. The equation in the documentation should be sufficient for people if there is need to find conversion factors, and can be implemented when required.

2021-01-05 16:47 UTC, sibirrer commented
Thank you very much! Looks all good and thanks for the updated documentation! There is one minor thing: There are two lines not yet tested: https://coveralls.io/builds/36090719/source?filename=lenstronomy/LensModel/Profiles/elliptical_density_slice.py
They are for single-valued input of the potential and deflection angles for outside the ellipse. Sorry to be petty here, just want to get to 100% test coverage of as many modules as possible

2021-01-06 11:12 UTC, LyneVdV commented
Done ! Don't worry, your are not being petty, just conscientious ;)

2021-01-06 12:58 UTC, sibirrer commented
Perfect, thank you! :)

2021-01-06 12:59 UTC, merged