add double gaussian magnification_finite computation and plot_quasar_images
sibirrer/lenstronomy pull request #235
Opened 2021-02-03 14:59 UTC by dangilman

I added the option to use two Gaussian source light profiles in the magnification_finite_adaptive computation, and the routine plot_quasar_images which produces plots of individual quasar images like the ones I often show

2021-02-03 15:00 UTC, dangilman commented
Two things: I removed the @jit decorators in my branch, that might be included in the pull request, maybe I should get rid of that. Also the test function for plot_quasar_images produces a plot, not sure if that will make the build fail

2021-02-03 17:19 UTC, sibirrer requested changes
my main comment is that plotting routines and analysis/calculations should be well separated (as good as possible), such that the there is not much duplication of code and routines and the plotting is clearly separated from a user API. Thanks!

2021-02-03 17:19 UTC, sibirrer commented on lenstronomy/LensModel/lens_model_extensions.py
> +    def plot_quasar_images(self, x_image, y_image, source_x, source_y, kwargs_lens,
this plotting function has a lot of calculations/ lines of code not specific to an execution of a plotting routine. Perhaps splitting these tasks might help with the code design. Just a though

2021-02-03 19:09 UTC, sibirrer requested changes
I have one minor request, otherwise looks great! Just waiting for the tests to pass too. Thanks

2021-02-03 19:09 UTC, sibirrer commented on lenstronomy/Util/magnification_finite_util.py
> +def setup(cosmo, lens_model, grid_radius_arcsec, grid_resolution, source_fwhm_parsec, source_light_model, z_source,
this routine name is a bit too unspecific. Could you add some naming that is better distinguishable from other routines and a bit more specific?

2021-02-04 04:11 UTC, sibirrer approved these changes

2021-02-04 04:14 UTC, sibirrer requested changes
Very minor (pedantic) request to make for an optimal test coverage: can you test the TORUS and raise statements too? I would like to approach 100% test coverage and all new lines of code being added to be tested. Thank you very much!

2021-02-04 16:28 UTC, dangilman commented
I just removed it since there is no way that anyone could have been using magnification_finite with shape='TORUS'. The required keywords could not have been specified for the source light model, so it would crashed.

2021-02-04 20:10 UTC, sibirrer approved these changes

2021-02-04 20:10 UTC, merged