spherical cored power profile
sibirrer/lenstronomy pull request #240
Opened 2021-03-01 17:56 UTC by dangilman

I added a new spherical cored power law profile defined in terms of a physical density parameter at r=0

2021-03-01 18:48 UTC, sibirrer requested changes
Looks great! I have only minor documentation suggestions and numerical stability questions for r=0. Waiting for tests and coverage report

2021-03-01 18:48 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/splcore.py
> +    rho(r, rc, g) = rho0 * (rc ^ g / (rc^2 + r^2)^(g/2))
can you change this formula to latex code? Like here: https://github.com/sibirrer/lenstronomy/blob/master/lenstronomy/LensModel/Profiles/p_jaffe.py
I try to convert all the model profiles to latex code for better rendering and convenient usage. Thanks

2021-03-01 18:48 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/splcore.py
> +    This lens profile corresponds to a spherical power law (CPL) mass distribution with logarithmic slope gamma (g) and
spherical power law does not match the CPL acronym. Perhaps mention the same name as the acronym.
Just to gross-check: there is no reference to this profile in the literature? You might want to add the reference later ;)

2021-03-01 18:48 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/splcore.py
> +    With respect to SPEMD, this model is different in that it is defined for gamma = 3, is circular, and written in terms
Perhaps state it clearly that this profile is ALSO defined for gamma=3. First time I read it I though it was solely defined at gamma=3.

2021-03-01 18:48 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/splcore.py
> +    param_names = ['rho0', 'center_x', 'center_y', 'rc', 'gamma']
here you specify the parameter 'rho0' while in the function arguments it's sigma0.

2021-03-01 18:48 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/splcore.py
> +    lower_limit_default = {'rho0': 0, 'center_x': -100, 'center_y': -100, 'rc': 1e-6, 'gamma': 1.+1e-6}
for the other cored density profiles, I am using the parameter name 'r_core'. Perhaps changing that name to make it more consistent might be helpful

2021-03-01 18:48 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/splcore.py
> +        cos = x_/r
is there a chance of deciding by zero here?

2021-03-01 18:48 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/splcore.py
> +        alpha_(x/y) = alpha_r * cos/sin(x/y / r)
is this line required?

2021-03-01 18:48 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/splcore.py
> +        gamma_tot = m2d / r ** 2 - kappa
division by r=0?

2021-03-01 18:48 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/splcore.py
> +        return rho0 * rc ** gamma / (rc**2 + r**2) ** (gamma/2)
could it be that for gamma being an integer, that the term gamma/2 in the exponent is inaccurate?

2021-03-01 18:48 UTC, sibirrer commented on test/test_LensModel/test_Profiles/test_splcore.py
> +class TestSPLCORE(object):
can you add tests for the derivatives and hessians for the coordinate (0,0)? I am not sure the calculation is stable there.

2021-03-01 18:50 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/splcore.py
> +        raise Exception('potential not implemented for this class')
can you do the raise test? For coverage :)

2021-03-01 19:59 UTC, sibirrer requested changes
some minor things I spotted

2021-03-01 19:59 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/splcore.py
> +    $\rho\left(r, \rho_0, r_c, \gamma\right) = \rho_0  \frac{{r_c}^\gamma}{\left(r^2 + r_c^2\right)^{\frac{\gamma}{2}}}$
here I mean with the .. math:: command (see other example)

2021-03-01 19:59 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/splcore.py
> +    This lens profile corresponds to a spherical power law (SPL) mass distribution with logarithmic slope gamma (g) and
I don't think you need the (g) anymore as gamma will be latex

2021-03-01 19:59 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/splcore.py
> +    The difference between this and EPL is that this model contains a core radius, is cir_coreular, and is also defined for gamma=3.
typo

2021-03-01 19:59 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/splcore.py
> +        $m_{\rm{3D}}\left(R\right) = 4 \pi r_{\rm{core}}^3 \rho_0 G\left(\frac{R}{r_{\rm{core}}}, \gamma\right)$
with .. math::

2021-03-01 19:59 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/splcore.py
> +    param_names = ['rho0', 'center_x', 'center_y', 'r_core', 'gamma']
rho0 -> sigma0

2021-03-01 22:01 UTC, sibirrer reviewed
Thanks a lot! It seems the assert_raise() statement gets not covered in coveralls. I am not sure why this is the case. Do you know why? Or perhaps chose the unites.TestCase format?

2021-03-02 00:01 UTC, dangilman commented on test/test_LensModel/test_Profiles/test_splcore.py
> +        npt.assert_raises(Exception, self.profile.function, (0., 0., 0., 0., 0.))
hmm no I don't know

2021-03-02 00:42 UTC, dangilman commented on test/test_LensModel/test_Profiles/test_splcore.py
> +        npt.assert_raises(Exception, self.profile.function, (0., 0., 0., 0., 0.))
I changed the assert_raises test to pass in individual arguments instead of a tuple of arguments.... someone on the internet said that might work

2021-03-02 01:11 UTC, dangilman commented on test/test_LensModel/test_Profiles/test_splcore.py
> +        npt.assert_raises(Exception, self.profile.function, (0., 0., 0., 0., 0.))
... and it did work!

2021-03-02 01:16 UTC, sibirrer approved these changes

2021-03-02 01:17 UTC, sibirrer commented on test/test_LensModel/test_Profiles/test_splcore.py
> +        npt.assert_raises(Exception, self.profile.function, (0., 0., 0., 0., 0.))
the internet...what would we do without it :)

2021-03-02 01:17 UTC, merged