Added a new fast implementation of the EPL profile
sibirrer/lenstronomy pull request #242
Opened 2021-03-02 16:37 UTC by ewoudwempe

This is the same profile as the already existing EPL profile, but my own implementation of it with Numba. Numba code is never pretty, but it is quite a bit faster than the existing PEMD models. Timings:
https://gist.github.com/ewoudwempe/10d47a7433afdb4d750dfad29e8dcd95
Comments? I suppose I'll have to make some tests too...
I could cache the parameter conversions, but it is a very small part of the computation times, so I don't think it's worth it.

2021-03-02 17:28 UTC, sibirrer requested changes
Overall looks great, and thanks also for the comprehensible testing! It really makes a difference. The tests failed (due to numba settings I guess). Perhaps you can move the @jit decorator on the ellipticity2phi_q transforms to your other PR dedicated to numba settings.

What is missing is test routines. You could add tests cross-comparing with the hyperbolic function implementation in 'EPL' and the numerical derivative tests: https://github.com/sibirrer/lenstronomy/blob/master/test/test_LensModel/test_numeric_lens_differentials.py
Thanks a lot and let me know if you have questions!

2021-03-02 17:28 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/epl_numba.py
> +    (theta_E / theta_E_gravlens) = sqrt[ (1+q^2) / (2 q) ]
I try to transition all formulas to latex and rendering in the documentation, primarily by requiring PRs and new code to do so. I'll do it right away for the EPL class and then you can adopt it here. Should be done soon on my side

2021-03-02 17:28 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/epl_numba.py
> +def param_transform(x, y, theta_E, gamma, e1, e2, center_x=0., center_y=0.):
can you add a description of the parameters?

2021-03-02 17:28 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/epl_numba.py
> +@nb.generated_jit(nopython=True, cache=True)
I am a bit worried about the fixed settings nopython=True and cache=True. Perhaps you can move this routine to the numba_util.py file and demand the same environment configurations as for the other @jit decorators.

2021-03-02 17:28 UTC, sibirrer commented on lenstronomy/Util/param_util.py
> +@jit
I see that you need those. Given that some other people manually out-commented previous decorators as a hack-fix, I'd like to first approve the PR with the fall-back and/or configurable numba settings

2021-03-04 06:23 UTC, sibirrer requested changes
This looks great! I have only very minor comments. I guess the other PR becomes obsolete then. I can try to turn off numba in the test coverage on my side indeed and this is not part of this PR. Thanks a lot!

2021-03-04 06:23 UTC, sibirrer commented on test/test_LensModel/test_numeric_lens_differentials.py
> +        lens_model = ['EPL']
I guess here you wanted the EPL_NUMBA model to be tested

2021-03-04 06:23 UTC, sibirrer commented on lenstronomy/Util/param_util.py
> +from lenstronomy.Util.numba_util import jit
I guess this is double imported

2021-03-04 06:23 UTC, sibirrer commented on lenstronomy/Util/numba_util.py
> +def generated_jit(nopython=nopython, cache=cache, parallel=parallel,fastmath=fastmath,error_model=error_model):
can you add a short description of this function and the definition arguments?

2021-03-04 06:23 UTC, sibirrer commented on lenstronomy/Util/numba_util.py
> +def nan_to_num_arr(x, posinf=1e10, neginf=-1e10, nan=0.):
I guess it's clear what this routine does but for better visibility in the documentation, can you add docstrings?

2021-03-04 06:23 UTC, sibirrer commented on lenstronomy/Util/numba_util.py
> +def nan_to_num_single(x, posinf=1e10, neginf=-1e10, nan=0.):
I guess it's clear what this routine does but for better visibility in the documentation, can you add docstrings?

2021-03-04 06:23 UTC, sibirrer commented on test/test_LensModel/test_Profiles/test_epl_numba.py
> +        #npt.assert_almost_equal(f_x, 0.)
is there a reason why this fails? (frankly, I have not tested that for either the SPEMD nor EPL model) It's fine if it's not tested as long as (I see that) the magnification is basically zero

2021-03-04 06:27 UTC, ewoudwempe commented on test/test_LensModel/test_Profiles/test_epl_numba.py
> +        #npt.assert_almost_equal(f_x, 0.)
Ah, it actually runs fine, I forgot to add that one back

2021-03-04 07:01 UTC, ewoudwempe commented
Everything passes :)
I think I addressed all your comments, but let me know otherwise!

2021-03-04 07:09 UTC, sibirrer commented
> Everything passes :)
> I think I addressed all your comments, but let me know otherwise!

Excellent! If you add the documentation strings for the definitions in the other PR (and probably sync it with this one not to create merge conflicts when merging one and then the other), we are done with it.

2021-03-04 07:09 UTC, sibirrer approved these changes

2021-03-04 07:20 UTC, ewoudwempe commented
Something went wrong here... let me try to fix...

2021-03-04 20:02 UTC, merged