Adds a safeguard that falls back to pure python if importing numba fails
sibirrer/lenstronomy pull request #243
Opened 2021-03-02 16:58 UTC by ewoudwempe

or if the environment variable NUMBA_DISABLE_JIT is non-empty.
Should solve #241. Can you confirm this works @dangilman?

2021-03-02 17:08 UTC, sibirrer requested changes
That's great! One thing that is still missing from what I added in #241 is a better option to configure the numba settings. On a cluster you need different settings and the current way is, well, a bit a hack in that regard (my code).

Let me know if it is not possible to perform a test as mentioned in the review comments. Thanks a lot!

2021-03-02 17:08 UTC, sibirrer commented on lenstronomy/Util/numba_util.py
> +    if numba_enabled:
Is it possible to change the numba_enabled variable and run a function with @jit decorator twice to test both options? Currently, depending on the environment, the tests are only executed once. Perhaps, to save guard failing of the tests if numba is not enabled, only explicitly test the numba_enabled=False on top of whatever the system option is (which, if installed properly, should be using numba by default)

2021-03-02 17:28 UTC, ewoudwempe commented on lenstronomy/Util/numba_util.py
> +    if numba_enabled:
Sure, you modify the decorator to always run the jitted function as well as the pure function, and then for the testing assert that the two functions return the same value. But then you want to separate between testing and real-world conditions? Because we don't want the everything to run twice if we are not running the test suite. Something like this could be used https://stackoverflow.com/questions/25188119/test-if-code-is-executed-from-within-a-py-test-session

2021-03-02 17:37 UTC, sibirrer commented on lenstronomy/Util/numba_util.py
> +    if numba_enabled:
I was more thinking of just executing one single call with a changed environment and then go back to the previous one by manually changing the numba_util.numba_enable variable (deep copy the previous one, setting it =False and then go back to the previous one). This would just ensure that both calls get executed at least once during test time.

2021-03-02 18:05 UTC, ewoudwempe commented on lenstronomy/Util/numba_util.py
> +    if numba_enabled:
Decorators immediately execute when defining a function to return a modified function, and although you could create a new wrapper function in the jit decorator, this will not work with Numba, as numba can only deal with jitted functions, and the wrapper is necessarily too general in its type assignments for numba to handle. Actually, my earlier suggestion would therefore also not work... hmm... I'm not sure how to handle that then. To 'switch' between jitted and non-jitted functions, the imported to-be-tested modules need to be reloaded somehow I think.

2021-03-02 18:25 UTC, sibirrer commented on lenstronomy/Util/numba_util.py
> +    if numba_enabled:
hmm...I see. So defining configurations needs to be done on a higher level with pre-configured configuration files. Can you move the @jit decorators in PR #242  on the ellipticity2phi_q and the nan_to_zero routines to this PR? Then we have all numba related parts affecting potentially other aspects all together in this PR. Thanks!

2021-03-02 19:07 UTC, ewoudwempe commented on lenstronomy/Util/numba_util.py
> +    if numba_enabled:
Done. I put the nan_to_zero in numba_util as it is quite specifically for numba, but if you want I can put it in util.py too. How do you want to solve the testing issue? Maybe add an extra testing module that specifically tests the numba stuff with numba on?

2021-03-02 20:00 UTC, sibirrer commented on lenstronomy/Util/numba_util.py
> +    if numba_enabled:
Thanks! For me it's less a testing issue than the ability for the user to change the numba settings pre-run. This might require a separate config file (which needs to be editable by the user and not be part of package itself to not being overwritten when lenstronomy is updated. I added @dangilman to this PR. Perhaps having a config import (in specific path as a yaml file, and if it does not exists, go back to default numba settings?

2021-03-02 20:11 UTC, dangilman commented on lenstronomy/Util/numba_util.py
> +    if numba_enabled:
yeah I guess you could make a numba_config.txt file and put it in the Util directory, then add something like this in numba_util.py

import inspect
file_path = inspect.getfile(inspect.currentframe()) + 'numba_config.txt' 
f = open(file_path, 'r')
config = eval(f.read())
if config==0:
    ~do something~
else:
    ~do something else~

2021-03-02 20:15 UTC, dangilman commented on lenstronomy/Util/numba_util.py
> +    if numba_enabled:
there is probably a more elegant way....

2021-03-03 20:03 UTC, sibirrer commented
I merged the PR with the yaml file configurations. It resulted in a conflict (hopefully minor) due to some duplication. This PR is otherwise ready to go. Thanks a lot for the patience!

2021-03-04 06:20 UTC, ewoudwempe commented
Thanks, I updated my PR. Perhaps you can turn off Numba for the coverage run by the way? The new function is implicitly tested in the other commit - good enough?

2021-03-04 06:27 UTC, sibirrer requested changes
Everything looks great! I commented in your other PR about docstrings in some of the definitions. These docstrings appear in the html documentation and it would be great if you could add some. Other than that it's great! Thank you very much!

2021-03-04 07:26 UTC, ewoudwempe commented
Sorry for the mess, but this one is good now. Apparently you need to not forget to rebase onto master after you do an interactive rebase to move some commits :)

2021-03-04 16:53 UTC, sibirrer commented
> Sorry for the mess, but this one is good now. Apparently you need to not forget to rebase onto master after you do an interactive rebase to move some commits :)

I don't see an added documentation to the routines in this PR. I added my comments on the other PR. Sorry for the slight confusion of doing two separate PR's

2021-03-04 19:55 UTC, ewoudwempe commented
I don't understand... I did add the documentation to this PR - if you go to files changed tab in github: line 76, 83, 96 contain (admittedly short) docstrings for the added numba nan_to_num functions, and the new @generated_jit decorator, part of commit 9c58f86. Or did you mean a more verbose multi-line docstring with all arguments on separate lines etc?

2021-03-04 20:01 UTC, sibirrer commented
I see, I though of doc strings for the individual parameters but the numba reference is sufficient (and probably most accurate). Thanks and sorry for the confusion!

2021-03-04 20:01 UTC, sibirrer approved these changes

2021-03-04 20:01 UTC, merged