Uldm profile (and correlated) update
sibirrer/lenstronomy pull request #255
Opened 2021-05-26 20:11 UTC by lucateo

Hi, 

as promised, I am making a new pull request with some updated features for the Uldm profile. In particular, I allow for the possibility of inserting a slope different from the one you would obtain by the so called "self gravitating soliton" (useful if you want to implement feedback arising from background potential). This is a feature I used in my recent work (2105.10873 for those who are interested) which made use of lenstronomy. 

I also modified the cored_density_mst.py file by inserting in all functions a rescaling with lambda_approx; the thing is, these profiles are used just in the MCMC inference to try to minimize covariances, but the MCMC inference done when you just subtract a perfect mass sheet from the cored profile doesn't give you back the "original" central convergence; if I worked out the math correctly (and I think I did, since with this correction I obtain what I expect), rescaling the functions with lambda_approx should overcome this issue.

Finally, I insert, always in cored_density_mst.py, a fourth profile which refers to Uldm profile. Given the structure of the function defined in that file, I just implement the possibility to use Uldm class in this "subtracted mass sheet degeneracy" way only for the standard soliton with slope = 8.

2021-05-26 20:42 UTC, sibirrer requested changes
This looks great! Thank you! I have some very minor documentation and formatting comments. For some reason, the coveralls coverage report was not triggered. I hope this will be done in the next push, but I don't see any untested lines myself.

2021-05-26 20:42 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/uldm.py
> +        \rho = \rho_0 (1 + a(r/r_c)^2)^{-\beta}
can you change the '\' into a '\\' in the math mode? Apparently then it gets recognized as a latex symbol.

2021-05-26 20:42 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/uldm.py
> +        \rho = \rho_0 (1 + a(r/r_c)^2)^{-\beta}
Can you also add the formula in terms of the parameters being used in this profile?

2021-05-26 20:42 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/uldm.py
> +    def alpha_radial(self, r, kappa_0, theta_c, slope = 8):
in the input argument, following PEP8, can you remove the spacing in slope=8?

2021-05-26 20:42 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/cored_density_mst.py
> +        return (f_cored_density - f_ms)/lambda_approx
would it be, perhaps, easier if you re-define kappa_ext instead of dividing the return arguments? This might save some code, i.e. kappa_ext = (1 - lambda_approx) / lambda_approx

2021-05-27 09:06 UTC, lucateo commented on lenstronomy/LensModel/Profiles/uldm.py
> +        \rho = \rho_0 (1 + a(r/r_c)^2)^{-\beta}
I am not so sure I understand, I tried to see other examples in lenstronomy and the solution I found is to change \ into \\, let me know if I should do something else.

2021-05-27 14:12 UTC, sibirrer approved these changes

2021-05-27 14:13 UTC, sibirrer commented
Thank you @lucateo ! This is grea! If there are some formatting issues coming up, I can easily change them later too.

2021-05-27 14:13 UTC, merged