Adding to sample the log of the parameters
sibirrer/lenstronomy pull request #272
Opened 2021-07-28 10:57 UTC by martin-millon

Hi @sibirrer,

I've added the option on my fork to sample the log of some parameters. It looks efficient when you have poorly constrained parameters and want to explore several orders of magnitude.  

If you think that could be useful to other users and if you are happy with this solution for the implementation, I can extend this to the other parameters (it works only for the lens parameters for the moment) and implement the test. 

There are also other commits to add some options here and there. I can remove this from this PR if necessary. 

Martin.

2021-07-28 16:29 UTC, sibirrer requested changes
Looks good overall and no major changes need to be done to be merged. You can leave the support currently for the lens model and we implement it as the feature gets requested/needed.

Can you add some test(s) making use of the feature as well? Thank you!

2021-07-28 16:29 UTC, sibirrer commented on lenstronomy/Conf/conf_default.yaml
> +  sersic_major_axis: True  # if True, defines the half-light radius of the Sersic light profile along the semi-major axis (which is the Galfit convention)
set =False for PR

2021-07-28 16:29 UTC, sibirrer commented on lenstronomy/LensModel/lens_param.py
> +        self.kwargs_logsampling = kwargs_logsampling
does this need to be a public variable?

2021-07-28 16:29 UTC, sibirrer commented on lenstronomy/LensModel/lens_param.py
> +                if name in kwargs_logsampling and not name in kwargs_fixed:
just a question: if you first let a parameter fixed and then let it vary in log space, might this cause problems?

2021-07-28 16:29 UTC, sibirrer commented on lenstronomy/LensModel/lens_param.py
> +                        else :
remove space between else and :

2021-07-28 16:29 UTC, sibirrer commented on lenstronomy/Plots/model_band_plot.py
> +                                 no_arrow=False, color_bar = True, **kwargs):
add description in doc string, remove space around '='

2021-07-28 16:29 UTC, sibirrer commented on lenstronomy/Sampling/parameters.py
> +        :param log_sampling_lens:
doc string

2021-07-28 16:29 UTC, sibirrer commented on lenstronomy/Sampling/parameters.py
> +        kwargs_logsampling_lens = [[] for i in range(len(self._lens_model_list))]
is this needed here or could you add it within _update_log_sampling? Just to have the __init__ a bit cleaner

2021-07-28 16:29 UTC, sibirrer commented on lenstronomy/Sampling/parameters.py
> +                raise TypeError("Bad format for constraint setting: got %s" % param_list)
Can you improve a bit the error message about how the format should look like?

2021-07-28 16:29 UTC, sibirrer commented on lenstronomy/Workflow/fitting_sequence.py
> +        self._updateManager.update_limits(change_source_lower_limit, change_source_upper_limit,change_lens_lower_limit,
add space after coma

2021-07-28 16:32 UTC, sibirrer commented
The tests fail due to your different setting for the R_sersic convention. Perhaps you can extend the tests such that they ask for the option being used and then assert two different values. Then the tests should pass regardless of the convention used locally.

2021-07-29 09:07 UTC, martin-millon commented on lenstronomy/LensModel/lens_param.py
> +                if name in kwargs_logsampling and not name in kwargs_fixed:
I think, in this case, you will need to use both the 'remove_fixed' option and the 'log_sampling_lens' option to let this parameter vary in logspace. It makes sense to me that this should be two separate operations. I will make some tests to check if everything is OK.

2021-07-29 09:19 UTC, martin-millon commented on lenstronomy/LensModel/lens_param.py
> +        self.kwargs_logsampling = kwargs_logsampling
This is called outside the class by the method Param.print_setting(). kwargs_fixed is public so I think kwargs_logsampling should be public as well, but I can change

2021-07-29 09:19 UTC, martin-millon commented on lenstronomy/Conf/conf_default.yaml
> +  sersic_major_axis: True  # if True, defines the half-light radius of the Sersic light profile along the semi-major axis (which is the Galfit convention)
OK, will change for the PR

2021-07-29 09:20 UTC, martin-millon commented on lenstronomy/LensModel/lens_param.py
> +                        else :
corrected

2021-07-29 09:24 UTC, martin-millon commented on lenstronomy/Plots/model_band_plot.py
> +                                 no_arrow=False, color_bar = True, **kwargs):
corrected

2021-07-29 09:24 UTC, martin-millon commented on lenstronomy/Sampling/parameters.py
> +        :param log_sampling_lens:
corrected

2021-07-29 09:40 UTC, martin-millon commented on lenstronomy/Sampling/parameters.py
> +        kwargs_logsampling_lens = [[] for i in range(len(self._lens_model_list))]
I coded it that way to avoid having the method _update_log_sampling reset the kwargs_logsampling, in a similar way than _update_joint_param() or _fix_joint_param(). Can be changed if you think that's necessary.

2021-07-29 09:40 UTC, martin-millon commented on lenstronomy/Sampling/parameters.py
> +                raise TypeError("Bad format for constraint setting: got %s" % param_list)
Corrected

2021-07-29 09:41 UTC, martin-millon commented on lenstronomy/Workflow/fitting_sequence.py
> +        self._updateManager.update_limits(change_source_lower_limit, change_source_upper_limit,change_lens_lower_limit,
corrected

2021-07-29 10:45 UTC, martin-millon commented on lenstronomy/LensModel/lens_param.py
> +                if name in kwargs_logsampling and not name in kwargs_fixed:
Ah yes, you are right, it will depend on the order you are making the changes... I'll correct this.

2021-07-29 13:12 UTC, martin-millon commented on lenstronomy/LensModel/lens_param.py
> +                if name in kwargs_logsampling and not name in kwargs_fixed:
OK, I think this is fine since the parameters in the arg only if not in kwargs_fixed. The log10 is applied only in the "args" and we keep always the 'kwargs' in direct space (also valid for the limit, etc.... ).

I have tried this sequence, and I did see any problems : 

`    ['update_settings',
     {
         'lens_add_fixed': [[0, ['theta_E']],
                               ]
     }
     ],

    ['update_settings',
     {
         'kwargs_constraints': {'log_sampling_lens': [
                 [0, ['theta_E']], 
             ]

         },
     }
     ],

    ['PSO',
     {
         'n_particles': n_particles,
         'n_iterations': n_iterations,
         'sigma_scale': 0.1,
     }
     ],

    ['update_settings',
     {
         'lens_remove_fixed': [[0, ['theta_E']],
                            ]
     }
    ],

    ['PSO',
     {
         'n_particles': n_particles,
         'n_iterations': n_iterations,
         'sigma_scale': 1.0,
     }
     ],`

2021-07-29 14:58 UTC, sibirrer commented on lenstronomy/LensModel/lens_param.py
> +                if name in kwargs_logsampling and not name in kwargs_fixed:
ah, yes log10 are only in the args and not kwargs, so this should be fine. Thanks for checking!

2021-07-29 15:00 UTC, sibirrer commented on lenstronomy/Sampling/parameters.py
> +        kwargs_logsampling_lens = [[] for i in range(len(self._lens_model_list))]
perhaps a short comment in the code for what is done here and why might help for future development and orientation. You can keep it there, thanks

2021-07-29 15:05 UTC, sibirrer requested changes
Thank you very much! I have only one minor request for testing a newly introduced raise statement, and a documentation/comment of what's happening with `kwargs_logsampling_lens`
Simon

2021-07-29 15:05 UTC, sibirrer commented on lenstronomy/Sampling/parameters.py
> +                raise TypeError(
can you test the raise? I know, the parameters.py file does not have these tests for the previous routines but I would like to enforce complete testing for all the PRs, thank you!

2021-07-30 14:10 UTC, merged

2021-07-30 14:10 UTC, sibirrer commented
Thank you!