Added an analytical lens equation solver and caustics routine for EPL…
sibirrer/lenstronomy pull request #286
Opened 2021-09-02 13:19 UTC by ewoudwempe

Quite a large PR, still needs quite some work before it's ready.
The advantages of using it are better accuracies, and better performance. This is illustrated in the following notebook:
https://gist.github.com/ewoudwempe/f2eefc2b3e31294c34c0e85c2c56b049

2021-09-02 15:52 UTC, sibirrer requested changes
This looks great! I suggest you move some files in different folders, as indicated. Perhaps you can make some function names a bit more intuitive, but perhaps added documentation will also do it. Other than that, documentation and testing is missing. I am particularly curious of tests matching for the same parameters for analytical vs numerical. Thanks a lot!

2021-09-02 15:52 UTC, sibirrer commented on lenstronomy/Analysis/epl_shear_solver.py
> +
this file is better suited in lenstronomy.LensModel.Solver

2021-09-02 15:52 UTC, sibirrer commented on lenstronomy/Analysis/epl_shear_solver.py
> +def lenseqtop_calcs(args, phi):
re-name function to better indicate what it does

2021-09-02 15:52 UTC, sibirrer commented on lenstronomy/Util/epl_util.py
> +
as this utilities are specific to the EPL model, it's probably better to have these functions in a separate Util folder within the LensModel module.

2021-09-02 15:52 UTC, sibirrer commented on lenstronomy/Util/epl_util.py
> +def brentq_nojit(f, xa, xb, xtol=2e-14, rtol=16*np.finfo(float).eps, maxiter=100, args=(), verbose=False):
is there a function within scipy or something similar that does the same thing? Just to avoid duplication where not necessary

2021-09-02 17:28 UTC, ewoudwempe commented on lenstronomy/Util/epl_util.py
> +def brentq_nojit(f, xa, xb, xtol=2e-14, rtol=16*np.finfo(float).eps, maxiter=100, args=(), verbose=False):
Well, this is almost a copy of scipy's version of scipy.optimize.brentq, with a few changes to make it numba-compatible. Directly using the scipy version is unfortunately not possible while keeping everything compiled. This was the easiest way (I think several other libraries also ship their own version of it). There may be some way to avoid it, but that would require some substantial effort I think...

2021-09-02 19:18 UTC, sibirrer commented on lenstronomy/Util/epl_util.py
> +def brentq_nojit(f, xa, xb, xtol=2e-14, rtol=16*np.finfo(float).eps, maxiter=100, args=(), verbose=False):
I see, so perhaps referencing in the documentation from where it comes from and why this needs to be there (numba) helps in the understanding and potential future development

2021-09-03 18:40 UTC, sibirrer requested changes
This looks great! I have some minor documentation and testing requests only

2021-09-03 18:40 UTC, sibirrer commented on lenstronomy/LensModel/Solver/epl_shear_solver.py
> +    if make_diagplot:
this part is neither tested nor documented. You may leave it there but then I suggest testing and documenting it

2021-09-03 18:40 UTC, sibirrer commented on lenstronomy/LensModel/Solver/epl_shear_solver.py
> +    else:
this part is not tested. Perhaps there is a way to do it when also choosing another test example

2021-09-03 18:40 UTC, sibirrer commented on lenstronomy/LensModel/Util/epl_util.py
> +
this file may benefit of better doc strings description the input and output parameters

2021-09-03 18:40 UTC, sibirrer commented on lenstronomy/LensModel/Util/epl_util.py
> +def brentq_nojit(f, xa, xb, xtol=2e-14, rtol=16*np.finfo(float).eps, maxiter=100, args=(), verbose=False):
perhaps you can run a test directly on this functions (as it is not @jit the coverage report can tell a bit more). You can e.g. test it against scipy

2021-09-03 20:33 UTC, sibirrer approved these changes
Looks all good. Just wondering whether some definitions could be set as private only meant to be accessed in a single file/class

2021-09-03 20:33 UTC, sibirrer commented on lenstronomy/LensModel/Solver/epl_shear_solver.py
> +
ah a minor thing: do you want to keep some of those definitions private (meaning not needed/wanted to have them accessed from other files/classes? If so, it would be good re-naming those starting with a '_'. That can just tell when refactoring is happening, which functions need to be preserved.

2021-09-03 21:22 UTC, ewoudwempe commented
Good idea, done :)

2021-09-03 21:32 UTC, merged