add mag_pert to source_position PointSource
sibirrer/lenstronomy pull request #292
Opened 2021-11-03 23:16 UTC by smericks

Added ability to apply magnification perturbations to images from a PointSource of type SOURCE_POSITION. This requires passing in a point source kwarg called 'mag_pert'. This change will allow users to make images from point sources with magnification errors.

2021-11-03 23:20 UTC, sibirrer requested changes
Thank you very much! Overall looks good. I have a few requests on testing and documentation, pending the integrated tests pass.

Also: please add your name and GitHub link to the AUTHORS.rst file
Simon

2021-11-03 23:20 UTC, sibirrer commented on test/test_PointSource/test_Types/test_ps_base.py
> +
Can you add tests for the other scenarios of this function

2021-11-03 23:20 UTC, sibirrer commented on lenstronomy/PointSource/Types/base_ps.py
> +
please document this definition

2021-11-03 23:20 UTC, sibirrer commented on lenstronomy/PointSource/Types/source_position.py
> +        mag_pert = kwargs_ps.get('mag_pert', 1)
please add a description of this variable/option in the definition of the SourcePosition class

2021-11-04 19:07 UTC, smericks commented
Thank you for the comments. All of the changes you've requested should be fixed. Please let me know if there are more changes needed.

Best,
Sydney

2021-11-04 20:55 UTC, sibirrer approved these changes

2021-11-04 20:55 UTC, merged

2021-11-04 20:56 UTC, sibirrer commented
Thank you very much @smericks and congratulations for your first contributions to lenstronomy!