First commit for Roman config with dummy variables
sibirrer/lenstronomy pull request #321
Opened 2022-06-12 11:46 UTC by Vikramb1

2022-06-12 12:39 UTC, sibirrer commented
Congratulations for your first PR @Vikramb1 !
A few things to start:
- please turn the .ipynb into a pure python file .py
- it turns out that the tests just failed not because of your added code but because some numerical tests were not defined as stable. I updated the lenstronomy main branch. Can you merge on your branch my new changes on my main branch to your fork? You can do it with the 'fetch' command: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork
- Please also add your name in the AUTHORS.rst file with your GitHub link :)

Once you did that, we can then look into the numbers and write test functions.

2022-06-28 22:40 UTC, sibirrer requested changes
Thanks for the update and filing in the tables! It looks great and I made some suggestion for improved documentation.
I also noticed that you took exposure time and number of exposures from the micro-lensing survey. This is an option (and this survey possibly is only going to be conducted in a subset of bandpass filters, so there might not be information of other bands). I would use as default option of the exposure time and number of exposures a design laid out here: https://roman.gsfc.nasa.gov/high_latitude_wide_area_survey.html

Let me know if you have questions!

2022-06-28 22:40 UTC, sibirrer commented on lenstronomy/SimulationAPI/ObservationConfig/Roman.py
> +                       'pixel_scale': 0.11,
just checking: when you computed the sky surface brightness, you used as the pixel area 0.11^2 and not 0.1^2?

2022-06-28 22:40 UTC, sibirrer commented on lenstronomy/SimulationAPI/ObservationConfig/Roman.py
> +    def __init__(self, band='F062', psf_type='GAUSSIAN', coadd_years=None):
the input argument 'coadd_years' is not required. This was specific for LSST. We can think of other options depending on the survey strategy

2022-06-28 22:40 UTC, sibirrer commented on lenstronomy/SimulationAPI/ObservationConfig/Roman.py
> +# sky brightness calculated using count rates per pixel given in website above
Did you take a median zodiac light? That's ok. Just be specific in the description here

2022-06-28 22:40 UTC, sibirrer commented on lenstronomy/SimulationAPI/ObservationConfig/Roman.py
> +# exposure time, number of exposures for F146 and F087: table 1 from https://iopscience.iop.org/article/10.3847/1538-4365/aafb69/meta#apjsaafb69t1fnd
This is not a specific enough description. There are different survey designs in the same table

2022-06-28 22:40 UTC, sibirrer commented on lenstronomy/SimulationAPI/ObservationConfig/Roman.py
> +# currently exposure_time set at 46.8 (same as F146), num_exposures set at 860, same as F087
these settings are for the micro-lensing survey, which is a 'special' mode of observation. It's great to have this mode implemented, but should not be the default one.

2022-06-28 22:40 UTC, sibirrer commented on lenstronomy/SimulationAPI/ObservationConfig/Roman.py
> +F062_band_obs = {'exposure_time': 46.8,
for these keyword argument lists, I would only put the 'seeing', 'magnitude_zero_point' and 'sky_brightness' arguments and strip the 'exposure_time' and 'num_exposures' to be added later within some 'survey_mode' argument. (i.e. micro-lensing survey vs deep field vs wide-and-deep survey etc). These latter arguments are operational choices while the first ones are inherently parameters of the telescope

2022-06-29 15:05 UTC, Vikramb1 commented on lenstronomy/SimulationAPI/ObservationConfig/Roman.py
> +                       'pixel_scale': 0.11,
Yes, I used 0.11^2.

2022-06-29 15:07 UTC, Vikramb1 commented on lenstronomy/SimulationAPI/ObservationConfig/Roman.py
> +    def __init__(self, band='F062', psf_type='GAUSSIAN', coadd_years=None):
I just removed it as an input.

2022-06-29 15:10 UTC, Vikramb1 commented on lenstronomy/SimulationAPI/ObservationConfig/Roman.py
> +# exposure time, number of exposures for F146 and F087: table 1 from https://iopscience.iop.org/article/10.3847/1538-4365/aafb69/meta#apjsaafb69t1fnd
Sorry, I have just made it mode clear which survey design it is.

2022-06-29 15:50 UTC, Vikramb1 commented on lenstronomy/SimulationAPI/ObservationConfig/Roman.py
> +F062_band_obs = {'exposure_time': 46.8,
Ok, that makes sense. I have gone ahead and removed the number of exposures and exposure time parameters and configured them based on a survey_mode input. I added functionality for the high latitude wide area survey and a microlensing survey. I am not sure where to find the deep field exposure parameters.

2022-06-29 15:55 UTC, sibirrer commented on lenstronomy/SimulationAPI/ObservationConfig/Roman.py
> +F062_band_obs = {'exposure_time': 46.8,
ok, then let's skip the deep field (it might also not happen, had vague memory of it). Thanks for the changes!

2022-06-29 16:11 UTC, Vikramb1 commented on lenstronomy/SimulationAPI/ObservationConfig/Roman.py
> +# sky brightness calculated using count rates per pixel given in website above
In the website, the count rates per pixel are only provided for minimum Zodiacal light. Is there a way to use those values to find the median and maxiumum corresponding values?

2022-06-29 16:17 UTC, sibirrer commented on lenstronomy/SimulationAPI/ObservationConfig/Roman.py
> +# sky brightness calculated using count rates per pixel given in website above
I see. Just noticed the image sensitivity calculator has this option: "Zodiacal light contributions (multiples of the minimum): 1.2, 1.4, 2.0, 3.5". We could try it later but so let's stick with the minimum for now.

2022-06-29 16:19 UTC, Vikramb1 commented on lenstronomy/SimulationAPI/ObservationConfig/Roman.py
> +# sky brightness calculated using count rates per pixel given in website above
Great!

2022-06-29 16:44 UTC, sibirrer requested changes
It looks great! You accidentally committed also a cached jupyter notebook.
The last part is now writing the test functions such that anyone can test whether the settings are going through.

You should add a file named 'test_roman.py' in the test folder mirroring the main lenstronomy code. You see an example test for the HST configuration e.g. here:
https://github.com/sibirrer/lenstronomy/blob/main/test/test_SimulationAPI/test_ObservationConfig/test_HST.py

You can follow basically the same structure and make sure all parts are covered.
You can run locally the tests on a python shell with:
$py.test test/test_SimulationAPI/<further_path_to_file>

Thanks a lot and let me know if you have questions!

2022-06-29 16:44 UTC, sibirrer commented on lenstronomy/SimulationAPI/ObservationConfig/.ipynb_checkpoints/Roman-checkpoint.ipynb
> +{
this file should not be committed.

2022-06-30 18:41 UTC, sibirrer commented
Nice! Tests pass and you did a great job testing the lines. You also added some raise testing. There are three remaining raise functions that are not tested (have a look at the coverage report above). Then we are good to merge :)

2022-06-30 20:36 UTC, sibirrer requested changes
Last minor request for change and then we are good

2022-06-30 20:36 UTC, sibirrer commented on lenstronomy/SimulationAPI/ObservationConfig/Roman.py
> +https://docs.google.com/spreadsheets/d/1pMUB_OOZWwXON2dd5oP8PekhCT5MBBZJO1HV7IMZg4Y/edit?usp=sharing for list of
Should this be here? I think this was used for LSST and not Roman configurations. You are giving the sources later on. Sorry, did not catch that, but otherwise looks all good and ready to merge

2022-06-30 20:47 UTC, Vikramb1 commented on lenstronomy/SimulationAPI/ObservationConfig/Roman.py
> +https://docs.google.com/spreadsheets/d/1pMUB_OOZWwXON2dd5oP8PekhCT5MBBZJO1HV7IMZg4Y/edit?usp=sharing for list of
Yes, just removed it!

2022-06-30 20:48 UTC, sibirrer approved these changes

2022-06-30 20:57 UTC, merged