Adding zeus as an alternative MCMC sampler
sibirrer/lenstronomy pull request #323
Opened 2022-07-08 11:17 UTC by nataliehogg

The zeus package has been added to the Sampler class in a new function called mcmc_zeus(). Zeus can be used by declaring 'sampler_type': 'ZEUS' in the dictionary passed to Fitting Sequence.

2022-07-08 15:19 UTC, sibirrer requested changes
Looks great! Tests will likely fail as zeus was not added to the environment.
I only have minor comments in addition. Let me know if you have questions!

2022-07-08 15:19 UTC, sibirrer commented on lenstronomy/Sampling/sampler.py
> +        import zeus
you probably need to put zeus in the requirements.txt and the setup.py (there in the same part as e.g. dynesty). I guess the tests fill fail as it can't find zeus in the environment that is created.

2022-07-08 15:19 UTC, sibirrer commented on test/test_Sampling/test_sampler.py
> +        n_walkers = 44
do you need that many walkers for testing? It's just that if tests run faster it is more convenient :)

2022-07-11 09:03 UTC, nataliehogg commented on lenstronomy/Sampling/sampler.py
> +        Lightning fast MCMC with zeus.
Sure thing!

2022-07-11 12:49 UTC, nataliehogg commented on lenstronomy/Sampling/sampler.py
> +        import zeus
I have added zeus to the requirements and setup, though the tests still fail because it can't find the back up file which is created for the chains when it looks to remove it (line 145 in test_sampler.py). I'm not sure how I can debug this without running the full tests each time, any tips?

2022-07-11 15:12 UTC, nataliehogg commented on lenstronomy/Sampling/sampler.py
> +        import zeus
Ah, I think I solved it, it's because by default zeus only saves to file after 100 steps and I'm only running for 4 in the test. I'll set the default for saving to file to one.

2022-07-11 15:56 UTC, sibirrer commented
who, the tests run and pass @nataliehogg!
Can you add a test function for running zeus through the FittingSequence() class too? See the test_fitting_sequence.py file.

2022-07-12 17:19 UTC, sibirrer approved these changes
Wonderful! I can approve it :)

2022-07-12 17:19 UTC, merged