add double power law profile
sibirrer/lenstronomy pull request #326
Opened 2022-07-10 16:34 UTC by dangilman

I added a double power law profile with flexible inner and outer logarithmic slopes inside and outside the scale radius

2022-07-10 17:02 UTC, sibirrer requested changes
Thank you for implementing the GNFW model!
I left some rather minor requests on testing.
Let me know if you have questions

2022-07-10 17:02 UTC, sibirrer commented on test/test_LensModel/test_Profiles/test_gnfw.py
> +        alpha_Rs = self.gnfw.rho02alpha(self.rho0, self.kwargs_lens['Rs'], self.kwargs_lens['gamma_inner'],
can you also test that alpha_Rs is the deflection angle at Rs?

2022-07-10 17:14 UTC, dangilman commented on test/test_LensModel/test_Profiles/test_gnfw.py
> +        alpha_Rs = self.gnfw.rho02alpha(self.rho0, self.kwargs_lens['Rs'], self.kwargs_lens['gamma_inner'],
done

2022-07-10 17:14 UTC, dangilman commented on lenstronomy/LensModel/Profiles/general_nfw.py
> +    upper_limit_default = {'Rs': 100, 'alpha_Rs': 10, 'center_x': 100, 'center_y': 100, 'gamma_inner': 2.9, 'gamma_outer': 10.0}
done

2022-07-10 17:15 UTC, dangilman commented on test/test_LensModel/test_Profiles/test_gnfw.py
> +    def test_lensing_quantities(self):
I don't think there is a limiting case for this profile because of the (1+x^2)^((n-g)/2) term

2022-07-10 17:16 UTC, dangilman commented on test/test_LensModel/test_Profiles/test_gnfw.py
> +        alpha_Rs = self.gnfw.rho02alpha(self.rho0, self.kwargs_lens['Rs'], self.kwargs_lens['gamma_inner'],
can you explain what you mean by define rho0?

2022-07-10 17:16 UTC, dangilman commented on lenstronomy/LensModel/Profiles/general_nfw.py
> +        if Rs < 0.0000001:
done

2022-07-10 17:16 UTC, dangilman commented on lenstronomy/LensModel/Profiles/general_nfw.py
> +        m_2d = 4 * rho0 * Rs * R ** 2 * gx / x ** 2 * np.pi
it should be now

2022-07-10 17:21 UTC, sibirrer commented on test/test_LensModel/test_Profiles/test_gnfw.py
> +        alpha_Rs = self.gnfw.rho02alpha(self.rho0, self.kwargs_lens['Rs'], self.kwargs_lens['gamma_inner'],
the self.rho0 term that is defined in the setup() function could be defined in this test function

2022-07-10 18:06 UTC, dangilman commented on test/test_LensModel/test_Profiles/test_gnfw.py
> +        alpha_Rs = self.gnfw.rho02alpha(self.rho0, self.kwargs_lens['Rs'], self.kwargs_lens['gamma_inner'],
done

2022-07-11 17:50 UTC, sibirrer approved these changes
I approve and add the references myself, since it's the first time :)

2022-07-11 17:50 UTC, merged